= Introduksjon
Direktoratet for forvaltning og IKT
2016-03-08

Denne veiledning er en av flere veiledere som beskriver hvordan EHF faktura og kreditnota skal benyttes i ulike bransjer i det norske markedet.

== Formål
Formålet med dette dokumentet er å beskrive og presisere bruk av EHF faktura og kreditnota for finansnæringen i Norge.

Med finansnæringen mener vi..

For å muliggjøre automatisering hos fakturamottaker, har det vært et mål at næringens behov bør uttrykkes i strukturerte elementer, ikke som fritekst-informasjon.

== Bakgrunn

Følgende typer av fakturaer har prosjektet funnet i bruk i finansnæringen, og disse er analysert videre for å spesifisere og avdekke informasjonsbehov og -krav. Det er ikke avdekket informasjonsbehov eller -krav som ikke kan uttrykkes strukturert i en EHF Faktura og kreditnota.

De ulike fakturatypene gjennomgås i egne kapitler, med beskrivelser og eksempler på utfylling i EHF.

. Leasing-fakturaer
* Vanlig leasing
* Avslutningsfaktura / utkjøp
* Lease build-up / renter før start
. Låne-fakturaer
. Factoring
. Salgsfaktura
* Lagerfinansiering
* Ad-hoc faktura
. Netting-faktura
