
[[mpkt]]
== Målepunkt

MålepunktID angis under levering `cac:Delivery` på en faktura. Levering består av leveringsdato og leveringssted. Leveringsdato anbefales å sette til siste dagen i perioden som fakturaen gjelder for. Leveringssted består av en identifikator for leveringsstedet samt adresse.

Dersom fakturaen gjelder kun ett målepunkt, legges målepunktID i identifikator-elementet under leveringssted. Siden alle målepunktID’er i Norge utgis av GS1 og er et såkalt Global Services Relation Number (GSRN) angis dette som attributt til målepunktID’en.

Gjelder fakturaen flere målepunkt, fylles ikke identifikator-elementet under leveringssted ut på faktuaen. Istedet benyttes levering på fakturalinje. Ref. <<_målepunktid>>

Anleggsadressen til målepunktet legges i adresse-elementene under levering

[source, xml]
.Eksempel på utfylling av målepunktID
----
<cac:Delivery>
  <cbc:ActualDeliveryDate>2013-02-15</cbc:ActualDeliveryDate>
  <cac:DeliveryLocation>
    <cbc:ID schemeID="GSRN">707057500022939815</cbc:ID>
    <cac:Address>
      <cbc:StreetName>Storgata</cbc:StreetName>
      <cbc:CityName>Bergen</cbc:CityName>
      <cbc:PostalZone>5000</cbc:PostalZone>
      <cac:Country>
        <cbc:IdentificationCode listID="ISO3166-1:Alpha2">NO</cbc:IdentificationCode>
      </cac:Country>
    </cac:Address>
  </cac:DeliveryLocation>
</cac:Delivery>
----
