= Factoring

NOTE: Med factoringfaktura menes at tredjepart (faktor) har overtatt kundefordringene, og denne utsteder fakturaen og angis som betalingsmottaker på fakturaen (PayeeParty)


Det er også viktig å merke seg at det kan forekomme factoring både for leasing, lån og vanlige salgsfakturaer.


== Informasjonsbehov

=== Fakturatype

For at mottaker skal kunne legge tilrette for automatiserte prosesser, anbefaler vi at fakturatype settes til verdien "393" som står for "factored  invoice".footnoteref:[fakturatype, I henhold til kodeliste UNCL 1001]

Fakturatype angis i elementet
https://vefa.difi.no/ehf/gefeg/invoice/2.0/gu1.htm?https://vefa.difi.no/ehf/gefeg/invoice/2.0/gu11.htm[`InvoiceTypeCode`] slik:

[source,xml]
----
<cbc:InvoiceTypeCode>393<cbc:InvoiceTypeCode>
----

=== Betalingsmottaker

En factoringfaktura er som spesifisert over her en faktura der betalingsmottaker er en annen part enn selger/leverandør. I en slik faktura, angis selger som vanlig i `AccountingSupplierParty`, mens betalingsmottaker (faktor) angis i elementet `PayeeParty`:


[source,xml]
----
<cac:PayeeParty>
	<cac:PartyIdentification>
		<cbc:ID schemeID="GLN">2298740918237</cbc:ID>
	</cac:PartyIdentification>
	<cac:PartyName>
		<cbc:Name>Faktoringselskap AS</cbc:Name>
	</cac:PartyName>
	<cac:PartyLegalEntity>
		<cbc:CompanyID schemeID="NO:ORGNR">989823401</cbc:CompanyID>
	</cac:PartyLegalEntity>
</cac:PayeeParty>

----

Eksempelfil:
https://github.com/OpenPEPPOL/finansveileder/blob/master/Examples/Factoring.xml[Factoring.xml]
