
= Factoring [[Factoring]]

NOTE: Med {factoring}faktura menes at tredjepart (faktor) har overtatt kundefordringene, og denne utsteder fakturaen og angis som betalingsmottaker på fakturaen (PayeeParty)


Det er også viktig å merke seg at det kan forekomme factoring både for leasing, lån og vanlige salgsfakturaer.


== Informasjonsbehov

=== Fakturatype

For at mottaker skal kunne legge tilrette for automatiserte prosesser, skal fakturatype settes til verdien "393" som står for "factored  invoice".footnoteref:[fakturatype, I henhold til kodeliste UNCL 1001]

Fakturatype angis i elementet {G_fakturatype} slik:

[source,xml]
.Eksempel fakturatype factoring
----
include::../Source/Factoring.xml[tags=type]
----

=== Betalingsmottaker

En factoringfaktura er som spesifisert over, en faktura der betalingsmottaker er en annen part enn selger/leverandør. I en slik faktura, angis selger som vanlig i {G_supplier}, mens betalingsmottaker (faktor) angis i elementet {G_payee}:

Videre beskrivelse av ulike parter i en faktura finner du i {V_roller}.

[source,xml]
.Eksempel på betalingsmottaker
----
include::../Source/Factoring.xml[tags=payee]
----

== Eksempelfil

Fullstendig EHF eksempelfil finnes vedlagt som
link:{sourcedir}/Source/Factoring.xml[Factoring.xml]
