= Forord

Denne veiledning er en av flere veiledere som beskriver hvordan EHF faktura og kreditnota skal benyttes i ulike bransjer i det norske markedet.

== Formål

Formålet med dette dokumentet er å beskrive og presisere bruk av EHF faktura og kreditnota for finansnæringen i Norge.

Med finansnæringen mener vi banker, forsikringsselskap, kredittforetak og finansieringsselskap.

== Referanser

EHF Implementasjonsguide:: https://test-vefa.difi.no/ehf/guide/invoice-and-creditnote/2.0/no/[]

Eksempelfiler::
https://github.com/OpenPEPPOL/finansveileder/tree/master/Examples[]

Vefa::
https://vefa.difi.no/[]

PEPPOL Transport-infrastruktur::
http://www.peppol.eu/ressource-library/technical-specifications/infrastructure-resources

== Fakturatyper

Følgende typer av fakturaer har prosjektet funnet i bruk i finansnæringen, og disse er analysert videre for å spesifisere informasjonsbehov og hvordan dette informasjonsbehovet kan dekkes i en EHF faktura eller kreditnota.

De ulike fakturatypene gjennomgås i egne kapitler, med beskrivelser og eksempler på utfylling i EHF.

. <<Leasing>>
* Vanlig leasing
* Avslutningsfaktura
* Fakturaer for interimsleie og renter før start
. <<Loans>>
* Næringslån med pant i eiendom
. <<Factoring>>
. <<Netting>>
. <<Sales>>
* Lagerfinansiering
* Ad-hoc faktura
