== Leasing-fakturaer


Med leasingfaktura menes fakturaer for innkreving av avtalt leasingbeløp for en gitt periode, her dekkes også leasingfakturaer som er delvis betalt samt leasing med startleie.

Prosjektgruppen har også sett på **lease build-up** og på **Avslutningsfaktura**. Disse to typene av fakturaer anses å være undertyper av generelle leasingfakturaer, og gruppen har ikke funnet at disse har ytterligere informasjonsbehov annet enn det som er skissert under. En **proforma avslutningsfaktura** anses å være en type tilbud uten fakturanummer, og faller dermed utenfor EHF.

I en leasingfaktura er det ønskelig/nødvendig å kunne angi informasjon om leie-objektet og det er viktig med informasjon om perioden/terminen fakuraen gjelder for.

For en leasingfaktura anbefaler vi at `<cbc:InvoiceTypeCode>` settes til verdien "394" for Lease-faktura. På denne måten kan mottaker automatisere prosesser basert på fakturatypen.

Informasjon om leie-objektet bør angis i elementet `cac:AdditionalDocumentReference`.

Eksempelet under viser hvordan man kan angi at leasingobjektet er en Toyota Yaris, med registreringsnummer AB12345:

[source,xml]
----
<cac:AdditionalDocumentReference>
<cbc:ID>Toyota Yaris, 1.3 liter<cbc:ID>
<cbc:DocumentType>Object</cbc:DocumentType>
</cac:AdditionalDocumentReference>

<cac:AdditionalDocumentReference>
<cbc:ID>AB12345</cbc:ID>
<cbc:DocumentType>License</cbc:DocumentType>
</cac:AdditionalDocumentReference>

----



Fakturaperiode kan i EHF oppgis både på dokumentnivå og på linjenivå, slik at man for de ulike fakturalinjene, kan angi spesifikke perioder/terminer. Periodene som angis på linjenivå bør ikke gå ut over den perioden som evt er angitt på dokumentnivå.


[source,xml]
----
<cac:InvoicePeriod>
	<cbc:StartDate>2014-01-16</cbc:StartDate>
	<cbc:EndDate>2014-02-16</cbc:EndDate>
</cac:InvoicePeriod>

----

Fullstendig EHF eksempelfil finnes vedlagt som *UC_finans_1.xml*
