
= Leasing - faktura for terminleie [[Leasing]]



NOTE: Med {leasing}-faktura menes fakturaer for innkreving av terminleie for avtalt leieperiode. Her dekkes også leasingfakturaer som er delvis betalt samt leasing med startleie.

Prosjektgruppen har også sett på fakturaer for **interimsleie** og **renter før start**, samt på **Avslutningsfaktura / utkjøpsfaktura**. Disse typene av fakturaer anses å være undertyper av generelle leasingfakturaer, og gruppen har ikke funnet at disse har ytterligere informasjonsbehov annet enn det som er skissert under.


== Informasjonsbehov


////////
=== Fakturatype

For at mottaker skal kunne legge tilrette for automatiserte prosesser, anbefaler vi at fakturatype i en leasingfaktura settes til verdien "394" som står for "Lease invoice".

Fakturatype angis i elementet https://vefa.difi.no/ehf/gefeg/invoice/2.0/gu1.htm?https://vefa.difi.no/ehf/gefeg/invoice/2.0/gu11.htm[`InvoiceTypeCode`] slik:

[source,xml]
.Eksempel fakturatype
----
<cbc:InvoiceTypeCode>394<cbc:InvoiceTypeCode>
----
////////

=== Leasingobjektet

Det er et behov og ønske om å angi informasjon om leasingobjektet på en strukturert måte i EHF, og følgende er prosjektgruppens anbefaling.

Informasjon om leasing-objektet bør ikke legges i fritekst-felter, men heller angis som tilleggsdokumentasjon, og dette gjøres i elementet {G_addDocs}, med {G_addDocType} = _Object_

Se også {V_addDocs}.



==== Biler/kjøretøy med registreringsnummer

For leasing av biler eller andre kjøretøy med registreringsnummer, anbefaler vi å oppgi både typen kjøretøy, samt registreringsnummeret.

Eksempelet under viser hvordan man kan angi at leasingobjektet er en Ford Mondeo, med registreringsnummer AB12345:

[source,xml]
.Eksempel leasing av bil
----
include::../Source/Leasing_Forskudd.xml[tags=object]
----
<1> Typen kjøretøy angis i ved å sette elementet {G_addDocType} til _Object_ i første instans av {G_addDocs}
<2> {G_addDocType} settes til verdien _License_ i andre instans av {G_addDocs}
<3> Selve registreringsnummeret oppgis i {G_addDocID}.

==== Anleggsmaskiner uten registreringsnummer

Ved leasing av anleggsmaskiner som ikke har registreringsnummer eller serienummer, angis kun en instans av {G_addDocs}, med {G_addDocType} satt til _Object_ <1>, slik:

[source,xml]
.Eksempel leasing av anleggsmaskiner
----
<cac:AdditionalDocumentReference>
<cbc:ID>Caterpiller D6R LGP Dozer<cbc:ID>
<cbc:DocumentType>Object</cbc:DocumentType> <1>
</cac:AdditionalDocumentReference>

----


==== Anleggsmaskiner med serienummer

For anleggsmaskiner med serienummer angis selve objektet som  i eksempelet over, mens serienummer angis med {G_addDocType} satt til _Serialnumber_.

[source,xml]
.Eksempel 2 leasing av anleggsmaskiner
----
<cac:AdditionalDocumentReference>
<cbc:ID>Volvo EC460 BLC<cbc:ID>
<cbc:DocumentType>Object</cbc:DocumentType>
</cac:AdditionalDocumentReference>

<cac:AdditionalDocumentReference>
<cbc:ID>80398</cbc:ID>
<cbc:DocumentType>Serialnumber</cbc:DocumentType>
</cac:AdditionalDocumentReference>

----

==== Skip med registreringsnummer

Ved leasing av skip med registreringsnummer, benyttes samme tekst i {G_addDocType} som ved leasing av bil/kjøretøy med registreringsnummer.

[source,xml]
.Eksempel leasing av skip
----
<cac:AdditionalDocumentReference>
<cbc:ID>Stinger 1100Z-DPH Lasteskip<cbc:ID>
<cbc:DocumentType>Object</cbc:DocumentType>
</cac:AdditionalDocumentReference>

<cac:AdditionalDocumentReference>
<cbc:ID>LK1234</cbc:ID>
<cbc:DocumentType>License</cbc:DocumentType>
</cac:AdditionalDocumentReference>

----

==== Software og Server løsninger

I tilfeller med leasing av software, servere eller annet IT-utstyr, henvises det oftest til ordrenummer/PO nummer, og ikke til et konkret leasingobjekt. I {G_addDocs} henvises det derfor kun til ordrenummeret, og dette angis i {G_ordre}.

[source,xml]
.Eksempel leasing av software
----

<cac:OrderReference>
	<cbc:ID>PO_12345</cbc:ID>
</cac:OrderReference>

...

<cac:AdditionalDocumentReference>
<cbc:ID>Se ordrenummer<cbc:ID>
<cbc:DocumentType>Object</cbc:DocumentType>
</cac:AdditionalDocumentReference>

----


=== Fakturaperiode

I en leasingfaktura er det ofte behov for å angi ulike fakturaperioder på ulike fakturalinjer. Derfor angis oftest fakturaperioden på linjenivå, ikke på dokumentnivå.

Fakturaperioden angis i elementet {G_linje_periode} slik:

[source,xml]
.Eksempel fakturaperiode på linje
----
include::../Source/Leasing_Forskudd.xml[tags=linje]
...
include::../Source/Leasing_Forskudd.xml[tags=periode]
...
----

=== Ordrenummer

Ordrenummer angis i elementet {G_ordre}.


[source,xml]
.Eksempel ordrenummer
----
include::../Source/Leasing_Forskudd.xml[tags=ordre]

----

=== Gebyr

En leasingavtale innebærer også ofte at det skal betales en del gebyrer, bl.a termingebyr.

EHF har egne elementer for å angi gebyrer, og disse skal også benyttes for å angi gebyrer knyttet til en leasingfaktura.

Videre detaljer om gebyr (og rabatter), finnes i {V_gebyr} og i {G_gebyr}[implementasjonsguiden]


Eksempelet under viser angivelsen av et termingebyr på kr. 65,-

[source,xml]
----
include::../Source/Leasing_Forskudd.xml[tags=gebyr]

----

== Eksempelfil

Fullstendig EHF eksempelfil finnes vedlagt som
link:{sourcedir}/Source/Leasing_Forskudd.xml[Leasing_Forskudd.xml]
